srl-labs/vscode-containerlab

package.json, src/commands/addToWorkspace.ts, src/commands/index.ts, src/extension.ts
=> Add lab folder to workspace

package.json, src/commands/index.ts, src/commands/openFolderInNewWindow.ts, src/extension.ts
=> Add command to open lab folder in a new window

src/commands/clabCommand.ts, src/commands/command.ts, src/commands/graph.ts
=> Open drawio

package.json, src/commands/index.ts, src/commands/inspect.ts, src/extension.ts, src/webview/inspect.css, src/webview/inspectHtml.ts
This introduces a webview for the inspect command. Closes #10
=> Inspect for labs

package.json, src/commands/capture.ts
=> add packetflixPort configuration for packet capture

src/commands/command.ts, src/commands/deploy.ts, src/commands/destroy.ts, src/commands/redeploy.ts, src/extension.ts
=> Add log viewing link in the spinner

package.json, src/clabTreeDataProvider.ts, src/topoViewer/backend/topoViewerWebUiFacade.ts
* Caches for nodes and interfaces
=> Performance

package.json, src/clabTreeDataProvider.ts, src/commands/deploy.ts, src/commands/destroy.ts, src/commands/redeploy.ts
* Add warning messages when deploy, redeploy and destroy with cleanup
* Implement caching for local and inspect labs with a 30 seconds TTL
=> Cleanup warnings and caches and Implement caching for local and inspect labs

CHANGELOG.md, package.json, src/clabTreeDataProvider.ts, src/commands/nodeImpairments.ts, src/topoViewer/backend/logger.ts
* Fixes for: Link Impairments via Webview (but remains buggy for some OS until the next clab release)
=> Fixes for: Link Impairments

.gitignore, src/clabTreeDataProvider.ts, src/extension.ts
- Selective refresh 
- Only refresh if cache expired
=> only refresh tree when there are changes

README.md
Installs should be unique. Downloads are not
=> Update README vsc badge to show installs instead of downloads

README.md, atest.clab.yml, package.json, src/commands/graph.ts, src/extension.ts
draw.io graph generation commands for horizontal and vertical layouts removed old webgraph
=> draw.io graph generation commands 

.gitignore, .vscodeignore, src/commands/inspect.ts, src/webview/inspect.css, src/webview/inspectHtml.ts
This overhauls the webview for the inspect labs command.
- More infos
- Table sorting
- Searchbar
=> Better Inspect labs webview

package.json, src/commands/deleteLab.ts, src/commands/index.ts, src/extension.ts
This allows to delete undeployed lab files from the tree
=> allow to delete undeployed labs

src/topoViewerEditor/webview-ui/topoViewerEditorEngine.ts
Fix the deletion of  single node with group
https://github.com/user-attachments/assets/d7d6cf86-6c9f-47e3-b9b2-9c92ad85aba0
=> fix-single-node-with-group-deletion

.gitignore, src/commands/deploy.ts, src/commands/destroy.ts, src/commands/graph.ts, src/commands/redeploy.ts, src/commands/utils.ts, src/extension.ts, src/topoViewer/backend/topoViewerAdaptorClab.ts, src/treeView/localLabsProvider.ts, src/treeView/runningLabsProvider.ts, test/helpers/utils-stub.ts, test/unit/commands/deploy.test.ts, test/unit/topoViewerEditor/preserveFieldsonSave.test.ts
* Fix topology loading error
* Enhance lab node caching in LocalLabTreeDataProvider and RunningLabTreeDataProvider for improved performance and stale entry management
* better locallabs cache
* removed unusful error message, reworked the caching strategy
=> Fixes and performance improvements (#190)

src/topoViewer/backend/topoViewerAdaptorClab.ts, src/topoViewer/backend/topoViewerWebUiFacade.ts, src/topoViewer/webview-ui/html-static/js/dev.js, src/topoViewer/webview-ui/html-static/template/vscodeHtmlTemplate.ts
https://github.com/user-attachments/assets/27b9e0dc-959e-42f6-9aa7-0e73c272ce40
=> integrate to Topoviewer

package-lock.json, src/topoViewer/common/templates/partials/navbar-buttons.html, src/topoViewer/common/templates/partials/navbar.html, src/topoViewer/common/templates/partials/panel-link-editor.html, src/topoViewer/common/templates/partials/panel-link.html, src/topoViewer/common/templates/partials/panel-node-editor-parent.html, src/topoViewer/common/templates/partials/panel-node-editor.html, src/topoViewer/common/templates/partials/panel-node.html, src/topoViewer/common/templates/partials/viewport-drawer-capture-sceenshoot.html, src/topoViewer/common/templates/partials/viewport-drawer-layout.html, src/topoViewer/common/templates/partials/viewport-drawer-topology-overview.html
Ausführung-01: Adjust html node, link, group panels
https://github.com/user-attachments/assets/6f16a007-7d32-47c8-8b9e-bef92ed72730
Ausführung-02: Adjust nav bar and its icons:
https://github.com/user-attachments/assets/abe44204-649a-4052-99a8-4d2aaeb268a6
=> HTML Templates adjusment

src/topoViewer/core/managerRegistry.ts, src/topoViewer/providers/topoViewerEditorWebUiFacade.ts, src/topoViewer/templates/partials/panel-node-editor-parent.html, src/topoViewer/types/topoViewerGraph.ts, src/topoViewer/utilities/annotationsManager.ts, src/topoViewer/webview-ui/managerFreeText.ts, src/topoViewer/webview-ui/managerGroupManagement.ts, src/topoViewer/webview-ui/managerGroupStyle.ts, src/topoViewer/webview-ui/managerSaveTopo.ts, src/topoViewer/webview-ui/managerUnifiedFloatingPanel.ts, src/topoViewer/webview-ui/topologyWebviewController.ts, src/topoViewer/webview-ui/uiHandlers.ts, test/unit/topoViewer/groupManagerBindings.test.ts, test/unit/topoViewer/managerRegistry.test.ts
This allows group styling and make right click the same between Viewer and Editor
=> Group style

src/topoViewer/webview-ui/managerAddContainerlabNode.ts
=> fix add node

src/topoViewer/webview-ui/topologyWebviewController.ts
=> rm cyEvent-> shift link add fix

package.json
Add some more default interface mappings, make it easy for people to get up and running with topoviewer
=> Add more default interface mappings

src/topoViewer/core/topoViewerAdaptorClab.ts, src/topoViewer/templates/partials/panel-node-editor.html, src/topoViewer/types/topoViewerGraph.ts, src/topoViewer/utilities/saveViewport.ts, src/topoViewer/webview-ui/managerNodeEditor.ts, src/topoViewer/webview-ui/tailwind.css, src/topoViewer/webview-ui/topologyWebviewController.ts
This adds all possible node settings in a updated Node Properties Panel
=> All possible Node settings

src/topoViewer/webview-ui/managerCopyPaste.ts
=> fix missing suffix when duplicatintg network-node

src/topoViewer/templates/partials/panel-network-editor.html
align network name field with other panel style
=> network editor panel - network name update

.gitignore, package.json, src/topoViewer/htmlTemplateUtils.ts, src/topoViewer/providers/topoViewerEditorWebUiFacade.ts, src/topoViewer/templates/partials/panel-node-editor.html, src/topoViewer/templates/partials/scripts.html, src/topoViewer/types/globals.d.ts, src/topoViewer/types/topoViewerGraph.ts, src/topoViewer/utilities/annotationsManager.ts, src/topoViewer/webview-ui/managerAddContainerlabNode.ts, src/topoViewer/webview-ui/managerCopyPaste.ts, src/topoViewer/webview-ui/managerCytoscapeBaseStyles.ts, src/topoViewer/webview-ui/managerNodeEditor.ts, src/topoViewer/webview-ui/managerSaveTopo.ts, src/topoViewer/webview-ui/managerUnifiedFloatingPanel.ts, src/topoViewer/webview-ui/managerViewportPanels.ts, src/topoViewer/webview-ui/tailwind.css, src/topoViewer/webview-ui/topologyWebviewController.ts
This feature adds node templates
=> Node templates

src/commands/attachShell.ts, src/commands/showLogs.ts, src/commands/ssh.ts, src/commands/telnet.ts, test/unit/commands/attachShell.test.ts
Use the node name rather than tree label
closes #343
=> Make the node terminal name unique

src/topoViewer/templates/partials/confirm-dialog.html
=> Fix Escape key issue in modal

src/helpers/filterUtils.ts, src/topoViewer/webview-ui/topologyWebviewController.ts
=> Add regex capture groups to bulk link creation

.gitignore, schema/clab.schema.json, src/topoViewer/templates/partials/panel-node-editor.html, src/topoViewer/utilities/saveViewport.ts, src/topoViewer/webview-ui/managerNodeEditor.ts, src/topoViewer/webview-ui/tailwind.css
https://github.com/user-attachments/assets/780d763c-1826-4b4c-b0a8-465db3bfbda6
As per https://github.com/srl-labs/containerlab/pull/2802 being merged. I now raise the following.
=> Add SR-SIM component support to TopoViewer

src/topoViewer/providers/topoViewerEditorWebUiFacade.ts, src/topoViewer/webview-ui/managerUnifiedFloatingPanel.ts, src/topoViewer/webview-ui/tailwind.css
- quick default
- dont close menu when adding a node, allows to add many nodes at once
=> Improve custom nodes
